-- Project 7 (Oracle) — DDL, DML, DCL, TCL, Joins, Set Operations
-- Adjust USER/ROLE names as per your environment for DCL.

-- =========================
-- Cleanup (idempotency-ish)
-- =========================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Employee';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Customer';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- =========
-- DDL: CREATE
-- =========
CREATE TABLE Customer (
  customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  first_name  VARCHAR2(50) NOT NULL,
  last_name   VARCHAR2(50) NOT NULL,
  email       VARCHAR2(120) UNIQUE
);

CREATE TABLE Employee (
  employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  first_name  VARCHAR2(50) NOT NULL,
  last_name   VARCHAR2(50) NOT NULL,
  email       VARCHAR2(120) UNIQUE,
  manager_id  NUMBER NULL,
  customer_id NUMBER NULL,
  CONSTRAINT fk_employee_manager FOREIGN KEY (manager_id) REFERENCES Employee(employee_id),
  CONSTRAINT fk_employee_customer FOREIGN KEY (customer_id) REFERENCES Customer(customer_id)
);

-- =========
-- DML: INSERT
-- =========
INSERT INTO Customer (first_name, last_name, email) VALUES ('Alice', 'Anderson', 'alice@example.com');
INSERT INTO Customer (first_name, last_name, email) VALUES ('Bob',   'Brown',    'bob@example.com');
INSERT INTO Customer (first_name, last_name, email) VALUES ('Cara',  'Clark',    'cara@example.com');

INSERT INTO Employee (first_name, last_name, email, manager_id, customer_id) VALUES ('Eve',  'Evans',  'eve@example.com',  NULL, NULL);
INSERT INTO Employee (first_name, last_name, email, manager_id, customer_id) VALUES ('Mark', 'Miller', 'mark@example.com', 1,    1);
INSERT INTO Employee (first_name, last_name, email, manager_id, customer_id) VALUES ('Nina', 'Nash',   'nina@example.com', 1,    2);

COMMIT;

-- =========
-- DML: SELECT
-- =========
SELECT * FROM Customer;
SELECT * FROM Employee;

-- =========
-- DML: UPDATE
-- =========
UPDATE Customer SET email = 'alice@newmail.com' WHERE first_name = 'Alice';

-- =========
-- DML: DELETE
-- =========
DELETE FROM Customer WHERE first_name = 'Cara';

COMMIT;

-- =========
-- TCL: SAVEPOINT / ROLLBACK / COMMIT
-- =========
SAVEPOINT before_temp_changes;
INSERT INTO Customer (first_name, last_name, email) VALUES ('Temp', 'User', 'temp@example.com');
ROLLBACK TO before_temp_changes;
COMMIT;

-- =========
-- DDL: ALTER
-- =========
ALTER TABLE Employee ADD (department VARCHAR2(50));
ALTER TABLE Employee MODIFY (department VARCHAR2(80));
ALTER TABLE Employee DROP COLUMN department;

-- =========
-- DDL: TRUNCATE (example table)
-- =========
CREATE TABLE Logs (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, message VARCHAR2(200));
INSERT INTO Logs (message) VALUES ('one');
TRUNCATE TABLE Logs;
DROP TABLE Logs;

-- =========
-- DCL: GRANT / REVOKE (requires privileges; adjust user/role as needed)
-- =========
-- Example:
-- GRANT SELECT, INSERT ON Customer TO some_user;
-- REVOKE INSERT ON Customer FROM some_user;

-- =========
-- JOINS between Employee and Customer
-- =========
-- INNER JOIN (employees linked to a customer)
SELECT e.employee_id, e.first_name AS emp_first, c.customer_id, c.first_name AS cust_first
FROM Employee e
JOIN Customer c ON e.customer_id = c.customer_id;

-- LEFT JOIN (all employees, with customer if present)
SELECT e.employee_id, e.first_name AS emp_first, c.customer_id, c.first_name AS cust_first
FROM Employee e
LEFT JOIN Customer c ON e.customer_id = c.customer_id;

-- RIGHT JOIN (all customers, with employee if present)
SELECT e.employee_id, e.first_name AS emp_first, c.customer_id, c.first_name AS cust_first
FROM Employee e
RIGHT JOIN Customer c ON e.customer_id = c.customer_id;

-- FULL OUTER JOIN (all employees and all customers)
SELECT e.employee_id, e.first_name AS emp_first, c.customer_id, c.first_name AS cust_first
FROM Employee e
FULL OUTER JOIN Customer c ON e.customer_id = c.customer_id;

-- =========
-- SET OPERATIONS
-- =========
-- For set operations, use compatible column lists and types.

-- UNION (distinct)
SELECT first_name FROM Customer
UNION
SELECT first_name FROM Employee;

-- UNION ALL (include duplicates)
SELECT first_name FROM Customer
UNION ALL
SELECT first_name FROM Employee;

-- INTERSECT (names appearing in both)
SELECT first_name FROM Customer
INTERSECT
SELECT first_name FROM Employee;

-- MINUS (Oracle) — in Customer but not in Employee
SELECT first_name FROM Customer
MINUS
SELECT first_name FROM Employee;


